name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
      - run: flutter pub get
      - run: dart analyze --fatal-infos --fatal-warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
      - run: flutter pub get
      - run: flutter test
